source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  faq:
    path: collections/faqs
    output: true
    description: 'Frequently Asked Questions'
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        name: New FAQ
        path: collections/schemas/faq.md
  post:
    path: posts
    output: true
    description: 'Blog posts'
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: pages
    output: true
    url:
    filter: strict
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: true
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_enabled_editors:
  - content
  - data
  - visual
base_url: 
data_config: {}
timezone: Etc/UTC
